import { StyleSheet } from 'react-native';
import colors from './colors';

const styles = StyleSheet.create({
    container: {
        flex: 20,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.white,
    },
    containerlogin:{
        flex: 1,
        backgroundColor: colors.lightGray,
    },
    rowContainer: {
        flex: 3,
        backgroundColor: colors.lightGray,
    },
    rowContent: {
        paddingHorizontal: 20,
        marginTop: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    title: {
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: colors.darkGray,
    },
    subtitle: {
        fontFamily: 'Outfit',
        fontSize: 24,
        color: colors.darkGray,
    },
    content: {
        fontFamily: 'Outfit',
        fontSize: 16,
        color: colors.darkGray,
        alignSelf: 'flex-start',
        marginLeft: 50,
        marginBottom: 8,
    },
    content2: {
      fontFamily: 'Outfit',
      fontSize: 16,
      color: colors.darkGray,
      alignSelf: 'flex-start',
      marginBottom: 8,
    },
    buttonContainer: {
        fontFamily: 'Outfit',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bluebutton: {
        fontFamily: 'Outfit',
        backgroundColor: colors.primary,
        borderRadius: 30,
        marginVertical: 10,
        width: 158,
        height: 41,
        justifyContent: 'center',
        alignItems: 'center',
    },
    whitebutton: {
        fontFamily: 'Outfit',
        backgroundColor: colors.white,
        borderColor: colors.primary,
        borderWidth: 2,
        borderRadius: 30,
        marginVertical: 10,
        width: 158,
        height: 41,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bluebuttonText: {
        color: colors.primary,
        fontSize: 16,
        fontWeight: 'bold',
    },
    whitebuttonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    rentbutton: {
        fontFamily: 'Outfit',
        backgroundColor: colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cancelbutton: {
      fontFamily: 'Outfit',
      backgroundColor: colors.red,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    textbox: {
        backgroundColor: colors.lightGray,
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 5,
        width: 280,
        height: 41,
        marginBottom: 20,
        fontSize: 16,
        color: colors.darkGray,
        borderWidth: 1,
        borderColor: colors.darkGray,
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 22,
    },
    carView: { 
        margin: 20,
        backgroundColor: colors.white, 
        borderRadius: 20,
        width: '90%',
        padding: 35,
        alignItems: 'center', 
        shadowColor: colors.black, 
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    topMargin: {
        marginTop: 20,
    },
    topMargin2: {
        marginTop: 40,
    }
});

export default styles;
